{{- if and .Values.single.enabled (not .Values.cluster.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corvo.fullname" . }}
  labels:
    {{- include "corvo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.single.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "corvo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "corvo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: corvo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - --bind
            - :8080
            - --raft-bind
            - :9400
            - --node-id
            - {{ include "corvo.fullname" . }}
            - --bootstrap=true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: raft
              containerPort: 9400
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "corvo.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
