{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-headless" (include "jobbie.fullname" .)) .Values.cluster.headlessServiceName }}
  labels:
    {{- include "jobbie.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "jobbie.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: raft
      port: {{ .Values.cluster.raftPort }}
      targetPort: raft
      protocol: TCP
{{- end }}
